name: Smoke Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
      AZURE_ACCOUNT_PASSWORD: ${{secrets.AZURE_ACCOUNT_PASSWORD}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      M365_ACCOUNT_NAME: ${{secrets.M365_ACCOUNT_NAME}}
      M365_ACCOUNT_PASSWORD: ${{secrets.M365_ACCOUNT_PASSWORD}}
      M365_TENANT_ID: ${{secrets.M365_TENANT_ID}}

      PROJECT_NAME: smoketest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          ref: projects

      - uses: OfficeDev/teamsfx-cli-action@test
        with:
          commands: provision
          folder: ./${{env.PROJECT_NAME}}
          subscription: ${{env.AZURE_SUBSCRIPTION_ID}}
      
      - uses: actions/upload-artifact@v2
        with:
          name: after-provision-fx-folder
          path: ./${{env.PROJECT_NAME}}/.fx

      - name: Azure Login to upload .fx.
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_STORAGE_CREDENTIALS}}

      - name: Upload .fx onto Azure Blob.
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.81
          inlineScript: az storage blob upload-batch -d artifacts --account-name ruhetest0722 -s ./${PROJECT_NAME}/.fx

      - uses: OfficeDev/teamsfx-cli-action@test
        with:
          commands: deploy
          folder: ./${{env.PROJECT_NAME}}

      - uses: OfficeDev/teamsfx-cli-action@test
        with:
          commands: validate
          folder: ./${{env.PROJECT_NAME}}
      
      - uses: OfficeDev/teamsfx-cli-action@test
        with:
          commands: build
          folder: ./${{env.PROJECT_NAME}}
      
      - uses: actions/upload-artifact@v2
        with:
          name: appPackage
          path: ./${{env.PROJECT_NAME}}/.fx/appPackage.zip

      - uses: OfficeDev/teamsfx-cli-action@test
        with:
          commands: publish
          folder: ./${{env.PROJECT_NAME}}